version: '3.8'

services:
  mysql:
    image: mysql
    container_name: checkers-back-mysql
    restart: unless-stopped
    networks:
      - default
  redis:
    image: redis
    container_name: checkers-back-redis
    restart: unless-stopped
    networks:
      - default
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    networks:
      - default