version: '3.8'

services:
  mysql:
    image: mysql
    container_name: checkers-back-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=marryp0ppins
    env_file:
      - .env
    networks:
      - default
  redis:
    image: redis
    container_name: checkers-back-redis
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - default