# Generated by Django 4.1.3 on 2023-06-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userOneTurn', models.BooleanField(default=True)),
                ('winner', models.CharField(blank=True, choices=[
                 ('USER_1', 'User 1'), ('USER_2', 'User 2'), ('DRAW', 'Draw')], max_length=6)),
                ('userOnePoints', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('userTwoPoints', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('startAt', models.DateTimeField(auto_now=True)),
                ('finishAt', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[
                 ('CREATED', 'Created'), ('IN_PROCESS', 'In Process'), ('FINISHED', 'Finished')], default='IN_PROCESS', max_length=10)),
                ('moves', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checkerId', models.PositiveSmallIntegerField()),
                ('newPositions', models.JSONField(blank=True, default=list)),
                ('isKing', models.BooleanField(default=False)),
                ('isLastMove', models.BooleanField(default=True)),
                ('isWhite', models.BooleanField(default=True)),
                ('isDead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('games', models.PositiveSmallIntegerField(default=0)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
