# Generated by Django 4.1.3 on 2023-04-01 11:25

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='game',
                to='app.game'),
        ),
        migrations.AddField(
            model_name='move',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='user_1',
            field=models.ForeignKey(
                on_delete=models.SET(
                    app.models.get_unknown_user),
                related_name='user_1',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='user_2',
            field=models.ForeignKey(
                on_delete=models.SET(
                    app.models.get_unknown_user),
                related_name='user_2',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
