# Generated by Django 4.1.3 on 2023-03-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username_1', models.CharField(db_index=True, max_length=16)),
                ('username_2', models.CharField(db_index=True, max_length=16)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('finish_at', models.DateTimeField()),
                ('moves', models.JSONField(default=dict)),
            ],
        ),
    ]
