# Generated by Django 4.1.3 on 2023-03-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userinfo_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='app_userinfo',
        ),
    ]
