# Generated by Django 4.1.3 on 2023-03-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='finish_at',
            field=models.DateTimeField(null=True),
        ),
    ]
