# Generated by Django 4.1.3 on 2023-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_game_finishat_alter_game_useronepoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='userOnePoints',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='userTwoPoints',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
