# Generated by Django 4.1.3 on 2023-04-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_game_status_alter_move_checker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='new_position',
        ),
        migrations.AddField(
            model_name='game',
            name='user_1_turn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='move',
            name='new_positions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('IN_PROCESS', 'В процессе'),
                                   ('FINISHED', 'Закончена')], default='CREATED', max_length=10),
        ),
    ]
