# Generated by Django 4.1.3 on 2023-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_move_new_position_game_user_1_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.CharField(default='', max_length=36),
        ),
    ]
