# Generated by Django 4.1.3 on 2023-04-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_game_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_1_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='user_1_win',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
