# Generated by Django 4.1.3 on 2023-04-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_game_user_1_points_game_user_1_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_2_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
