# Generated by Django 4.1.3 on 2023-05-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_game_user_2_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user_1_win',
        ),
        migrations.AddField(
            model_name='game',
            name='winer',
            field=models.CharField(blank=True, choices=[('USER_1', 'User 1'), ('USER_2', 'User 2'), ('DRAW', 'Draw')], max_length=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IN_PROCESS', 'In Process'), ('FINISHED', 'Finished')], default='CREATED', max_length=10),
        ),
    ]
