# Generated by Django 4.1.3 on 2023-05-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_game_user_1_win_game_winer_alter_game_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='winer',
            new_name='winner',
        ),
    ]
