# Generated by Django 4.1.3 on 2023-05-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_winer_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='uuid',
        ),
    ]
