# Generated by Django 4.1.3 on 2023-05-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_game_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
