# Generated by Django 4.1.3 on 2023-03-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authenticationusergroups_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='authentication_user',
        ),
    ]
